version: '3.8'  # Specify the version of Compose

services:
  myapp:
    build:
      context: .  # The directory where Dockerfile is located
      dockerfile: Dockerfile  # Dockerfile name
    volumes:
      - .:/app  # Mounts current directory to /app in the container
    ports:
      - "8080:80"  # Map port 8080 on your host to port 80 in the container
